name: PHP Unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, sqlite, curl
      - name: Install composer deps
        run: composer install --no-interaction --prefer-dist
      - name: Prepare environment
        run: cp phpunit.xml.dist phpunit.xml || true
      - name: Run tests
        run: vendor/bin/phpunit --colors=always -v
